version: '3'
services:
  anaconda3:
    container_name: anaconda3c
    #image: continuumio/anaconda3
    deploy:
      resources:
        limits:
           memory: 2048M
        reservations:
           memory: 2048M
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./:/data/git
    command: tail -f /dev/null
    build: 
      context: ./
      dockerfile: Dockerfile
